CSNRecicla/Controllers/PontosDeColetaController.cs
using CSNRecicla.Data;
using CSNRecicla.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSNRecicla.Controllers
{
    [Authorize]
    public class PontosDeColetaController : Controller
    {
        private readonly ApplicationDbContext DbContext;
        private readonly UserManager<Usuario> UserManager;
        public PontosDeColetaController(ApplicationDbContext dbContext, UserManager<Usuario> userManager)
        {
            DbContext = dbContext;
            UserManager = userManager;
        }
        // GET: PontosDeColetaController
        public IActionResult Index()
        {
            IEnumerable<PontoDeColeta> pontosDeColetas = DbContext
                .PontoDeColetas.Include(p => p.Usuario).Where(p => p.UsuarioId == UserManager.GetUserId(User));
            List<PontoDeColetaViewModel> pontosViewModel = new List<PontoDeColetaViewModel>();
            // TODO: utilizar AutoMapper
            foreach(var p in pontosDeColetas)
            {
                pontosViewModel.Add(new PontoDeColetaViewModel()
                {
                    Nome = p.Nome,
                    Descricao = p.Descricao,
                    CEP = p.CEP,
                    Endereco = $"{p.Numero}, {p.Logradouro}, {p.Cidade} - {p.Estado}",
                    NumeroDoc = p.Usuario.NumeroDoc
                });
            }
            return View(pontosViewModel);
        }

        // GET: PontosDeColetaController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: PontosDeColetaController/Create
        public IActionResult Cadastrar()
        {
            return View();
        }

        // POST: PontosDeColetaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Cadastrar(PontoDeColetaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    PontoDeColeta pontoDeColeta = new PontoDeColeta()
                    {
                        CEP = model.CEP,
                        Cidade = model.Cidade,
                        Descricao = model.Descricao,
                        Estado = model.Estado,
                        Logradouro = model.Logradouro,
                        Nome = model.Nome,
                        Numero = model.Numero,
                        Pais = model.Pais,
                        Telefone = model.Telefone,
                        UsuarioId = UserManager.GetUserId(User)
                    };
                    DbContext.PontoDeColetas.Add(pontoDeColeta);
                    DbContext.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }

        // GET: PontosDeColetaController/Edit/5
        public IActionResult Editar(int id)
        {
            return View();
        }

        // POST: PontosDeColetaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PontosDeColetaController/Delete/5
        public IActionResult Excluir(int id)
        {
            return View();
        }

        // POST: PontosDeColetaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Excluir(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public IActionResult Encontrar()
        {
            return View();
        }
    }
}

CSNRecicla/Controllers/PontuacaoController.cs
using CSNRecicla.Data;
using CSNRecicla.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSNRecicla.Controllers
{
    [Authorize]
    public class PontuacaoController : Controller
    {
        private readonly ApplicationDbContext DbContext;
        private readonly UserManager<Usuario> UserManager;

        public PontuacaoController(ApplicationDbContext dbContext, UserManager<Usuario> userManager)
        {
            DbContext = dbContext;
            UserManager = userManager;
        }

        public IActionResult Index()
        {
            PontuacaoViewModel pontuacao = new PontuacaoViewModel();
            pontuacao.Pontos = DbContext.Users
                .Where(u => u.Id == UserManager.GetUserId(User))
                .FirstOrDefault().Pontos;
            return View(pontuacao);
        }

        public IActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registrar(RegistroDePontosViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await DbContext.Users.FindAsync(UserManager.GetUserId(User));
                    user.Pontos = (model.Quantidade * 7) + user.Pontos;
                    DbContext.Attach(user);
                    DbContext.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View(model);
                }
            }
            return View(model);
        }
    }
}

CSNRecicla/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSN Recicla</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light ">
            <a class="navbar-brand" asp-action="Index" asp-controller="Home" style="padding-left: 25px"><img src="~/assets/logo.jfif" style="width: 60%" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                </ul>

                <div class="float-right" style="padding-right: 15px">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <span><strong>@User.Identity.Name</strong></span>
                        <a class="btn btn-secondary btn-header btn-header2" asp-controller="Pontuacao" asp-action="Index">Ver pontuação</a>
                        <a class="btn btn-secondary btn-header btn-header2" asp-controller="PontosDeColeta" asp-action="Cadastrar">Cadastrar ponto de coleta</a>
                        <a class="btn btn-secondary btn-header btn-header2" asp-controller="Acesso" asp-action="Logout">Sair</a>
                    }
                    else
                    {
                        <a asp-action="Registrar" asp-controller="Acesso" class="btn btn-secondary btn-header" style="margin-right: 10px;">Criar conta</a>
                        <a asp-action="Index" asp-controller="Acesso" class="btn btn-secondary btn-header btn-header2">Entrar</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Desenvolvido por Matriz 2x2 © 2021
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>