CSNRecicla/Models/PontuacaoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSNRecicla.Models
{
    public class PontuacaoViewModel
    {
        public int Pontos { get; set; }
        public string UsuarioId { get; set; }
    }
}

CSNRecicla/Controllers/PontuacaoController.cs
using CSNRecicla.Data;
using CSNRecicla.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSNRecicla.Controllers
{
    [Authorize]
    public class PontuacaoController : Controller
    {
        private readonly ApplicationDbContext DbContext;
        private readonly UserManager<Usuario> UserManager;

        public PontuacaoController(ApplicationDbContext dbContext, UserManager<Usuario> userManager)
        {
            DbContext = dbContext;
            UserManager = userManager;
        }

        public IActionResult Index()
        {
            PontuacaoViewModel pontuacao = new PontuacaoViewModel();
            pontuacao.Pontos = DbContext.Users
                .Where(u => u.Id == UserManager.GetUserId(User))
                .FirstOrDefault().Pontos;
            return View(pontuacao);
        }

        public IActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registrar(RegistroDePontosViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await DbContext.Users.FindAsync(UserManager.GetUserId(User));
                    user.Pontos = (model.Quantidade * 7) + user.Pontos;
                    DbContext.Attach(user);
                    DbContext.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View(model);
                }
            }
            return View(model);
        }
    }
}

CSNRecicla/Controllers/TrocasPontuacaoController.cs
using CSNRecicla.Data;
using CSNRecicla.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSNRecicla.Controllers
{
    [Authorize]
    public class TrocasPontuacaoController : Controller
    {
        private readonly ApplicationDbContext DbContext;
        private readonly UserManager<Usuario> UserManager;

        public TrocasPontuacaoController(ApplicationDbContext dbContext, UserManager<Usuario> userManager)
        {
            DbContext = dbContext;
            UserManager = userManager;
        }
        public IActionResult Index()
        {
            PontuacaoViewModel pontuacao = new PontuacaoViewModel();
            pontuacao.Pontos = DbContext.Users
                .Where(u => u.Id == UserManager.GetUserId(User))
                .FirstOrDefault().Pontos;
            return View(pontuacao);
        }

        public IActionResult Status()
        {
            return View();
        }
    }
}

CSNRecicla/Views/Pontuacao/Index.cshtml
@model PontuacaoViewModel

@{
    ViewData["Title"] = "Meus Pontos";
}
<script src="https://kit.fontawesome.com/39e3608a27.js" crossorigin="anonymous"></script>

<main class="container-fluid principal">
    <div class="row">
        <div class="col-12 col-md-6">
            <div class="boxes">
                <h1>Cadastrar Pontos</h1>
                <i class="fas fa-plus-circle"></i>
                <h3 class="points">Adicione seus pontos já!</h3>
                <br>
                <a asp-action="Index" asp-controller="Home" class="btn btn-primary btn-main">Saiba mais</a>
                <a asp-action="Registrar" asp-controller="Pontuacao" class="btn btn-primary btn-main">Fazer cadastro</a>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="boxes">
                <h1>Meus Pontos</h1>
                <i class="fas fa-recycle"></i>
                <h1 class="points"><strong>@Model.Pontos PTS</strong> </h1>
                <a asp-action="Index" asp-controller="TrocasPontuacao" class="btn btn-primary btn-main">Fazer troca</a>
            </div>
        </div>
    </div>
</main>